name: Deploy Docker Image

on:
  workflow_dispatch:
    inputs:
      StackName:
        type: choice
        description: Environment Name
        options:
          - placeholder-option
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to selected environment
        run: |
          stack_name=${{ github.event.inputs.StackName }}
          echo "Deploying to environment: $stack_name"
          # Add your deployment commands here, using the stack_name
