name: Terraform Plan and Apply

on:
  push:
    branches:
      - '**'
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "github-testing"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "GitHub-terraform-testing"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform Plan and Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -out=tfplan.out \
            -var="PAT=${{ secrets.PAT }}" 

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan.out

      - name: Save Terraform State
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform state pull > terraform.tfstate

      - name: Upload Terraform State
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: terraform.tfstate
