name: Update Workflow Inputs

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
    
jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run update script
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          chmod +x .github/update_workflow.sh
          .github/update_workflow.sh $PAT
