name: Update Workflow Inputs

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every hour

jobs:
  update-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Run update script
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        chmod +x update_workflow.sh
        ./update_workflow.sh $PAT
